spring.application.name=recruitment-backend
server.port=8088

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/recruitment_db
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

# JWT
app.jwt.secret=RecruitmentAppSecretKey2026VeryLongSecretKeyForJWTTokenGeneration123456
app.jwt.expiration-ms=86400000

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=uploads

# Serve uploaded static files
spring.web.resources.static-locations=classpath:/static/,file:uploads/
